### ISSUE TITLE
Audio and timer pause when in the pause menu

### ISSUE THREAD

**Issue by Shiggy-dev** [exscape/Celeste-FewerVisualDistractions#1]
this is a very good mod however my only issue with it is that it pauses the audio and timer when in the pause menu with no way to disable this behavior

**Comment by exscape** [comment]
Ohh, thank you for the issue! That's a feature I added for myself, that isn't in the source code because it doesn't fit with the mod theme, but I forgot to remove from the binaries when I released it.  
I'll release an updated version in a few hours or so.

**Comment by exscape** [comment]
Fixed in v0.9.1 ([released on GameBanana](https://gamebanana.com/mods/491205)).  
No code changes on GitHub since the code in question was never committed in the first place.
