### ISSUE TITLE
breaks the savestate feature of speedrun tools

### ISSUE THREAD

**Issue by Shiggy-dev** [exscape/Celeste-FewerVisualDistractions#2]
using the latest version (0.9.3) causes the savestate feature of speedrun tools to break, specifically when creating a savestate you can no longer input anything nor load the savestate. reloading the current map with f5 allows the usage of the created savestate but the same issue occurs again when creating another savestate

https://github.com/exscape/Celeste-FewerVisualDistractions/assets/90344513/d527ac4b-f4a0-4cfb-8599-0d1d2ebad540

the freezes in midair are the creation of the savestate, it doesnt appear well in the video but for a split second the death wipe shows up and disappears.
the master switch does not appear to change this behavior

**Comment by exscape** [comment]
Thanks for the report, and for including the video!

I had a look at this and traced the issue to the screen wipe removal in this mod. It changes the level's screen wipe to null (and then restores it again), and Speedrun Tool uses the screen wipe's onComplete action to unfreeze the game after saving/loading. So when the wipe is removed, the action never runs.

I made a quick fix that makes everything work when screen wipes are enabled in this mod (and so also when the master switch is off), but I'll try to rework the screen wipe patch such that you can disable screen wipes AND have save states working properly.

**Comment by exscape** [comment]
[FewerVisualDistractions-0.9.4.zip](https://github.com/exscape/Celeste-FewerVisualDistractions/files/14510511/FewerVisualDistractions-0.9.4.zip)

@Shiggy-dev Could you test this version?  
If it works (it works fine for me) I'll upload it to GameBanana later today or tomorrow, unchanged.

When screen wipes are enabled (i.e. unmodded), everything works as-is now.  
When they are disabled, v0.9.4 will execute any onComplete actions for screen wipes the next frame, which at least solves the hangs with Speedrun Tool.

**Comment by Shiggy-dev** [comment]
this does seem to work for me as well, thank you!
